#!/bin/bash

ls /usr/bin | awk '(NR-105178554)%251==0' | ./run | grep .so |

sed "s/[=][>].*//g" | sed 's/(.*//' | sed 's/\/.*\///' |
sed 's/^ *//g' | sed 's/^[ \t]*//g' |  
#sed "s/[(].*[)]//g" |
#sed "s/[=][>].*//g" | 
#sed 's/^[ \t]*//g' | 
sort -u
